### ISSUE TITLE
auto_test fail at run_test.go line 56

### ISSUE THREAD

**Issue by unravel11** [OpenRHINO/RHINO-CLI#81]

**Comment by LI-Mingyu** [comment]
run_test.go succeeded in local environment (docker desktop) but failed in Github Actions (https://github.com/OpenRHINO/RHINO-CLI/actions/runs/4950873004/jobs/8855065395)

<img width="267" alt="image" src="https://github.com/OpenRHINO/RHINO-CLI/assets/20229719/189ed652-3655-451b-afcc-de6fa81a197f">

**Comment by LI-Mingyu** [comment]
This bug should be fixed in the RHINO-Operator repo.  The auto test workflow for RHINO-CLI uses https://github.com/OpenRHINO/RHINO-Operator/blob/main/install-rhino-operator.yaml to deploy the operator. However, this yaml declared the v1alpha1 API, while the image used in the yaml, openrhino/controller:latest, was upgraded and requires the v1alpha2 API. So the test environment was broken.

**Comment by LI-Mingyu** [comment]
It was fixed by the commit "upgraded the one-step-installation yaml file to v1alpha2" (https://github.com/OpenRHINO/RHINO-Operator/commit/b1bcaf9eff6d6ac372a148e2809eae24157bf544)
